### ISSUE TITLE
关于骨粉问题 

### ISSUE THREAD

**Issue by 1504879303** [Caishangqi/GonerAge#11]
建议能用 ，大大降低效率，根源魔法需要不少花，不会真要跑图把。改成可以对草地使用。。。

**Comment by Caishangqi** [comment]
> 建议能用 ，大大降低效率，根源魔法需要不少花，不会真要跑图把。改成可以对草地使用。。。

盘马斯配置禁用,无法直接从配置文件修改

**Comment by 1504879303** [comment]
呕
