### ISSUE TITLE
EmbersConstruct方镁钒模具无法放进冲模加工台

### ISSUE THREAD

**Issue by HeXiaoYou** [Caishangqi/GonerAge#13]
经过多次测试，生方镁钒模具无法放进冲模加工台，烧制过的也不能。
<img width="293" alt="截屏2020-06-17 下午2 07 52" src="https://user-images.githubusercontent.com/66977341/84861755-57a86400-b0a4-11ea-89d6-53374fb75d2a.png">

**Comment by Caishangqi** [comment]
![image](https://user-images.githubusercontent.com/39553613/84873545-40339180-b038-11ea-9dbc-d3b8ab95d0b9.png)
![image](https://user-images.githubusercontent.com/39553613/84873580-50e40780-b038-11ea-91d9-e49ed9b0ea57.png)

请核实

**Comment by HeXiaoYou** [comment]
属实是我眼瞎
