### ISSUE TITLE
匠魂工具无法修复

### ISSUE THREAD

**Issue by HeXiaoYou** [Caishangqi/GonerAge#14]
经过测试，损坏和非损坏的匠魂工具都无法用矿物锭修复。由于EmbersConstruct的问题。不确定能否用磨制工具修复。
<img width="329" alt="截屏2020-06-17 下午2 36 48" src="https://user-images.githubusercontent.com/66977341/84863826-32b5f000-b0a8-11ea-9293-3b3c7d98e88b.png">

**Comment by Caishangqi** [comment]
> 经过测试，损坏和非损坏的匠魂工具都无法用矿物锭修复。由于EmbersConstruct的问题。不确定能否用磨制工具修复。
> <img alt="截屏2020-06-17 下午2 36 48" width="329" src="https://user-images.githubusercontent.com/66977341/84863826-32b5f000-b0a8-11ea-9293-3b3c7d98e88b.png">

## 请核实是否重启过客户端更新至最新的配置文件
![image](https://user-images.githubusercontent.com/39553613/84873898-be903380-b038-11ea-908a-8fad337652cb.png)

**Comment by HeXiaoYou** [comment]
确实为最新客户端，工具和金属摆放好后会出现修复后的工具，但是无法拿取，现在进行磨制工具能否修复的测试

**Comment by Caishangqi** [comment]
> 确实为最新客户端，工具和金属摆放好后会出现修复后的工具，但是无法拿取，现在进行磨制工具能否修复的测试

一些工具需要磨制工具才可以修复,属于设定内容
