### ISSUE TITLE
BetweenLand炽炎铁锭无法在余烬熔炉中融化（大概）

### ISSUE THREAD

**Issue by HeXiaoYou** [Caishangqi/GonerAge#15]
交错次元的炽炎铁锭有余烬的融化配方，但是无法在余烬的熔炉中融化进行锻造，不确定是时间不够还是Bug
（已经下线了所以没来得及截图）
（如果又是我搞错了提前跟菜蛇道歉）

**Comment by Caishangqi** [comment]
> 交错次元的炽炎铁锭有余烬的融化配方，但是无法在余烬的熔炉中融化进行锻造，不确定是时间不够还是Bug
> （已经下线了所以没来得及截图）
> （如果又是我搞错了提前跟菜蛇道歉）
### 我没有看到对应的合成配方,只有其原矿的合成配方
![image](https://user-images.githubusercontent.com/39553613/84881902-5b57ce80-b043-11ea-8d4e-480f760d5a56.png)
### 原矿合成配方
![image](https://user-images.githubusercontent.com/39553613/84882031-82160500-b043-11ea-9a25-f21e14def66e.png)
### 其对应压印材料
![image](https://user-images.githubusercontent.com/39553613/84882089-95c16b80-b043-11ea-8748-451ac0be4806.png)
