### ISSUE TITLE
关于TAIGA中瓦雷利亚矿石的产量

### ISSUE THREAD

**Issue by HeXiaoYou** [Caishangqi/GonerAge#27]
（纯属个人观点，可能是我脸太黑导致的）
瓦雷利亚矿石的生成分布为地狱Y=0-128（全高度），权重是10。昨天在地狱刨了一两个小时最后只在地狱门口刨了两块（脸太黑了）
我觉得可以把矿石的分布高度给一个限制，比如0-96，这样可以相对容易的找到矿石，保护地狱生态环境，防止地狱岩土质疏松容易坍塌（不是）
或者将瓦雷利亚矿石的矿物锭产量提高为0.8或者1，也可以缓解矿石稀缺的问题
或者根据冰与火之歌小说里的设定给瓦雷利亚一个合成方式（并不）

**Comment by Caishangqi** [comment]
改了,所有矿石权重x0.25

**Comment by HeXiaoYou** [comment]
（语文不好可能理解错了）
但是，×0.25岂不是更少了（危）

**Comment by Caishangqi** [comment]
> （语文不好可能理解错了）
> 但是，×0.25岂不是更少了（危）

是的，减少了生成量,因为增大了基础矿物的产量

**Comment by HeXiaoYou** [comment]
感觉不太够的亚子…
建议增加可以用矿石换矿石的机制
比如两个钷或者钯换一个瓦雷利亚，这样不仅价格合理也可以避免萌新跳级获得矿石，就是不知道插件允不允许

**Comment by HeXiaoYou** [comment]
球球菜蛇把瓦雷利亚矿石弄得好得到点吧
是真的太难找到了，比振金还难，某种意义上算是科技线Bug了（胡扯）
