### ISSUE TITLE
沉浸工程工程师合成台破坏时会销毁所有材料

### ISSUE THREAD

**Issue by HeXiaoYou** [Caishangqi/GonerAge#28]
沉浸工程的工程师合成台被破坏时会吞掉所有其中的材料

**Comment by HeXiaoYou** [comment]
除此之外，在用制作部件蓝图制作物品时，无法正常放入材料（会在背包里乱跳），导致无法制作物品（我制作的是真空管）

**Comment by Caishangqi** [comment]
> 除此之外，在用制作部件蓝图制作物品时，无法正常放入材料（会在背包里乱跳），导致无法制作物品（我制作的是真空管）

按键问题已解决
