### ISSUE TITLE
Mac端无法正常显示Artisan Workshop相关合成

### ISSUE THREAD

**Issue by HeXiaoYou** [Caishangqi/GonerAge#29]
（仅Mac端出了问题，过来说一下，影响不大）
在制作物品时，如果有需要在Artisan Workshop制作的物品，将不会显示配方（比如沉浸工程蓝图）

**Comment by Caishangqi** [comment]
> （仅Mac端出了问题，过来说一下，影响不大）
> 在制作物品时，如果有需要在Artisan Workshop制作的物品，将不会显示配方（比如沉浸工程蓝图）

系统修复工程请反馈相关系统Issue界面,不在我能力范围内,次客户端原生支持win 8 -win10系统。
