### ISSUE TITLE
建议加个mod：TE5(热力膨胀5

### ISSUE THREAD

**Issue by 1449169** [Caishangqi/GonerAge#35]
TE热力膨胀，顶级好mod！
推动我的世界狂潮！不仅支持服务器，而且内容丰富，简直是魔法与科技的融合！
热力膨胀最初只是BC建筑的一个附属模组，但如今它已经发生了翻天覆地的变化！
它具有设计多台机器的科技树，平衡和灵活的合成表，现在是修改Minecraft游戏的基础模组之一，自发布以来，Redstone flux（RF）能源网络已经得到大多数科技向模组及其附属模组的支持。
目前服务器只有四个科技向mod，IE沉浸工程及其附属和TR科技复兴，添加TE热力膨胀这个模组，可以加强科技生产力，通过此模组的热力管道使复杂的科技生产线能够自动化，变得更加便捷。并且添加更多的产能机器，在除了无脑冲IE的柴油发电机的情况下有了更多选择，并且可以使IE及其附属更好的联动。
此模组还有一些实用工具，如谐振背包，谐振电容，储物箱，保险箱，便携储罐等等。还有一些更加实用的机器，如附魔机，蓄水器，水产捕捞器，经验液化器等等。本模组的感应炉配合IE使用能更加便捷、快速的制作出钢锭，使需要大量钢锭的IE沉浸工程模组不用一直憋钢。
总而言之，服务器科技向mod有点少，IE和TR这个mod显得有些许单薄，加个TE彳亍不？

**Comment by Caishangqi** [comment]
着涉及到服务器题材,**19世纪**。虽然热力膨胀有许多生产类型物品比如造价很便宜的蒸汽机,以及含方便的管道系统,但是它本身是脱离旧时代的题材的,他的出现会迫使许多玩家制造TE机械(因为他们很便宜)而不会制造IE或者RT机械导致合成不平滑并且偏科

**Comment by 1449169** [comment]
服务器的题材19世纪那加个rc铁路感觉不错，rc正好有蒸汽机之类的感觉和蒸汽殖民这个主题比较搭。
考虑一下？

**Comment by Caishangqi** [comment]
rc 会考虑加入，因为此模组可以实现较远距离的自动化，我需要平衡rc模组的发电设施和配方合成，这需要一定时间。
