### ISSUE TITLE
匠魂工具升级

### ISSUE THREAD

**Issue by 1449169** [Caishangqi/GonerAge#36]
服务器里面的匠魂工具如果没有用纸质配件的话一把情况下只有3个强化槽。此模组为匠魂工具添加了经验值熟练度系统，你的匠魂工具在使用时可以获得经验，例如用镐挖掘方块，用剑击杀生物。每升一级可以多获得一个强化槽，升级之后下次升级所需要的经验值会有所提升。也可以在文件里更改升级所需经验值和等级上限。

**Comment by Caishangqi** [comment]
因为添加了Taiga模组，如果使用过多升级会导致过多属性出现，则会导致匠魂工具nbt数量过多而造成服务器崩溃的严重bug，在通常情况下是会开启但是由于加入Taiga和petwer特性过多则关闭。并且每次大任务完成后均有匠魂强化奖励
