### ISSUE TITLE
银树木板无合成

### ISSUE THREAD

**Issue by Threxion** [Caishangqi/GonerAge#48]
xinxi姐把我赶来了
5 5 5
*神秘银树和宏伟木板不能合成
太草了
据木头的工作台造的木头没手搓得多差评（小声bb
wight不是op差评
*然后是发现carryon有时候在搬蜂箱（未来mc的野生蜂箱）时会触发bug，无限放
wight不能秒boss
*以及地狱太安全了，我想当op来产怪，地狱不该是和和气气的！
地狱应该充满妹子！（我就想想就好）
芜湖！
这波啊，这波是bug葱鸡

**Comment by Threxion** [comment]
啊还有就是服务器设置进群问题比较好，要不然例如NNX这样的人再来一个就不好了
我的愚见

**Comment by Caishangqi** [comment]
不处理人际问题,板块必须关闭.
