### ISSUE TITLE
TAIGA中的烈金无法正常融合

### ISSUE THREAD

**Issue by HeXiaoYou** [Caishangqi/GonerAge#51]
![2020-07-03_17 01 39](https://user-images.githubusercontent.com/66977341/86452686-3c4d8200-bd4f-11ea-840b-068cfe79c5a0.png)
![2020-07-03_17 01 48](https://user-images.githubusercontent.com/66977341/86452688-3d7eaf00-bd4f-11ea-8684-4b3e0a3467b7.png)
如图，按照正确的配方融合三种金属无法得到狄奥尼（烈金），确认搅拌器有能量且配方为泰伯利亚+碎金+塞姆（地动合金）

**Comment by Caishangqi** [comment]
已反馈作者，非配方问题
