### ISSUE TITLE
极端问题处理与游戏环境改善(人文项)

### ISSUE THREAD

**Issue by Threxion** [Caishangqi/GonerAge#52]
wight的“遗书”
        嘿，看到标题，相信你也知道我是谁了，就算留在关闭板块里也一样吧。
        是的，我是第一个去暮色，第一个去阿图姆，第一队杀boss…（除了第一个被ban  XD）曾经的服务器战力天花板，祖安钢琴家，带恶人
         但这都不是我写下这书的原因——我利用漏洞刷东西了。
         如果觉得没意思，也请你看完，你可能会有所收获
         服务器非常好，优化也不错；优点是腐竹非常勤快，尽管还有学业，人也非常的核善，还是一个渣男（划掉），OP也很严谨，令人佩服。
游戏内容修改了很多，难度变大，为了让你不会因为一年就能肝完而感到无聊，服务器做了许多贴近实际的配方改动，非常的人性化🙃
        最后请小心一个叫verynice的人
        *下面是一个故事，仅仅是故事而已*
        V嫉妒W，就把他拉了屏蔽，借口是不喜欢看他说话，并且一直拉拢W的队友he
直到W发展出了电力机器，V就贴过来讨好W，借用机器。
由于机器效率翻倍，材料减半的V很快也做出了自己的机器，之前所谓“方便交流”制作的传送门也拆掉了，并且拉黑了W。其实W看得出来做传送门只是方便她自己使用电力机器，只是懒得理会她的小伎俩而已。
        就这样，V很多次用“问过W了”为借口找he要东西，制造W与he的矛盾，最后W骂走了he，he赌气加入了very，这无论何时看来都是一种叛变与挖墙脚。
挖走he的时候因为洋洋得意漏了马脚，当天的证据W发进了游戏群4周目相册中，无人问津。
        在我看来，V这种心xiao机jian表ren在现实生活中没少被针对和挨打，因为针对别人挺有一套的，W也只是懒得去理会她的宫斗戏小技巧而已。

        如果你是蛇，或者猫猫，真的钛棒了，我又在你们心里活了一次XP
        猫，在最后这段时间有你一起，真的很开心，你经常会去无条件的帮助别人，从来不会让他人不舒服；虽然总是嘴上说着在摸鱼，其实从不摸鱼，真的很棒。
        蛇的话，等你下次新周目记得喊我哦，咱们说好了😚
毕竟xinxi姐说了不能留，也只能这样了。虽然很不甘
对不起了，刷东西搞事情，添了很多麻烦
如果还有机会，估计不会了
祝你和老板娘天长地久，早日结婚😏
这是一个反派最后的倔强
加油！祝愿服务器越来越好！

**Comment by HeXiaoYou** [comment]
泪目

**Comment by Threxion** [comment]
> 泪目

你也少被骗点，好(老)兄(苦)弟(力)

**Comment by Caishangqi** [comment]
是的，服务器这种攀比行为很严重,我已经交给Xinxi处理,由于我本人只维护技术方面故此板块会留给Xinxi作为参考。

**Comment by Rubywu-Xin** [comment]
从聊天记录和群内气氛可以看出,两人是完全对你持厌恶态度的,我不知道之前你对她们俩做出了什么冒犯行为,但是单独从挖墙角来看这事意见不是很好的事情,破坏了本该和谐的服务器发展进度,但是这可能与我和 @Caishangqi 之前设定的游戏目标有关,喜欢竞争并不是一件坏事只不过把这种竞争放在他人的游戏体验上在我认为是很不对的,我会改善游戏环境并且把游戏迷目标模糊化或者彻底清除,主服的主要目的就是休闲,从她们的口中的"霸服"本身并不是我所期待的GonerAge与发展。

另外，统计结果出现后并不是所有人都是清白的,这取决于Caishangqi对刷东西的定以,若自动化刷沙机也算上的话,几乎所有人都算是刷物品的,若不算上，你和NXX的占比超过平均值。这个“定以”由我和Caishangqi之后做决定。

最后,这里面存在一个因果逻辑,若你是在He走后开始刷东西的其实可以理解,但若你在其之前就开始刷东西则你将无法为此行为做出合理的解释。游戏本身就是一起娱乐的，若平凡出现排斥,压迫,我是必将其修改的。你可以私聊我或者在下方留言来解释你为什么被她们讨厌之类的。

**Comment by Rubywu-Xin** [comment]
> wight的“遗书”
> 嘿，看到标题，相信你也知道我是谁了，就算留在关闭板块里也一样吧。
> 是的，我是第一个去暮色，第一个去阿图姆，第一队杀boss…（除了第一个被ban XD）曾经的服务器战力天花板，祖安钢琴家，带恶人
> 但这都不是我写下这书的原因——我利用漏洞刷东西了。
> 如果觉得没意思，也请你看完，你可能会有所收获
> 服务器非常好，优化也不错；优点是腐竹非常勤快，尽管还有学业，人也非常的核善，还是一个渣男（划掉），OP也很严谨，令人佩服。
> 游戏内容修改了很多，难度变大，为了让你不会因为一年就能肝完而感到无聊，服务器做了许多贴近实际的配方改动，非常的人性化🙃
> 最后请小心一个叫verynice的人
> _下面是一个故事，仅仅是故事而已_
> V嫉妒W，就把他拉了屏蔽，借口是不喜欢看他说话，并且一直拉拢W的队友he
> 直到W发展出了电力机器，V就贴过来讨好W，借用机器。
> 由于机器效率翻倍，材料减半的V很快也做出了自己的机器，之前所谓“方便交流”制作的传送门也拆掉了，并且拉黑了W。其实W看得出来做传送门只是方便她自己使用电力机器，只是懒得理会她的小伎俩而已。
> 就这样，V很多次用“问过W了”为借口找he要东西，制造W与he的矛盾，最后W骂走了he，he赌气加入了very，这无论何时看来都是一种叛变与挖墙脚。
> 挖走he的时候因为洋洋得意漏了马脚，当天的证据W发进了游戏群4周目相册中，无人问津。
> 在我看来，V这种心xiao机jian表ren在现实生活中没少被针对和挨打，因为针对别人挺有一套的，W也只是懒得去理会她的宫斗戏小技巧而已。
> 
> ```
>     如果你是蛇，或者猫猫，真的钛棒了，我又在你们心里活了一次XP
>     猫，在最后这段时间有你一起，真的很开心，你经常会去无条件的帮助别人，从来不会让他人不舒服；虽然总是嘴上说着在摸鱼，其实从不摸鱼，真的很棒。
>     蛇的话，等你下次新周目记得喊我哦，咱们说好了😚
> ```
> 
> 毕竟xinxi姐说了不能留，也只能这样了。虽然很不甘
> 对不起了，刷东西搞事情，添了很多麻烦
> 如果还有机会，估计不会了
> 祝你和老板娘天长地久，早日结婚😏
> 这是一个反派最后的倔强
> 加油！祝愿服务器越来越好！

从聊天记录和群内气氛可以看出,两人是完全对你持厌恶态度的,我不知道之前你对她们俩做出了什么冒犯行为,但是单独从挖墙角来看这事意见不是很好的事情,破坏了本该和谐的服务器发展进度,但是这可能与我和 @Caishangqi 之前设定的游戏目标有关,喜欢竞争并不是一件坏事只不过把这种竞争放在他人的游戏体验上在我认为是很不对的,我会改善游戏环境并且把游戏迷目标模糊化或者彻底清除,主服的主要目的就是休闲,从她们的口中的"霸服"本身并不是我所期待的GonerAge与发展。

另外，统计结果出现后并不是所有人都是清白的,这取决于Caishangqi对刷东西的定以,若自动化刷沙机也算上的话,几乎所有人都算是刷物品的,若不算上，你和NXX的占比超过平均值。这个“定以”由我和Caishangqi之后做决定。

最后,这里面存在一个因果逻辑,若你是在He走后开始刷东西的其实可以理解,但若你在其之前就开始刷东西则你将无法为此行为做出合理的解释。游戏本身就是一起娱乐的，若平凡出现排斥,压迫,我是必将其修改的。你可以私聊我或者在下方留言来解释你为什么被她们讨厌之类的。

**Comment by Threxion** [comment]
我真的不理解，为什么会被针对；这个事情对我而言真的很在意，一开始的理由是以我嘴臭为籍屏蔽我，我很公道的说，我没有做对不起他们两个的事情，人格担保，可能是我平常一些行为让他们讨厌了吧；我挺直的，喜欢不喜欢都挂在嘴边，这应该是作为我嘴臭讨厌我的理由，但这不只我一个人；太明显的针对了，而且证据也有，我藏进了第四周目截图里。目的太明显了，我都不知道对我这么强烈的恨是什么。
谢谢，如果可以留下来，万分感谢
这样公道的处理对我已经是最善良的结果了。

**Comment by Rubywu-Xin** [comment]
> 我真的不理解，为什么会被针对；这个事情对我而言真的很在意，一开始的理由是以我嘴臭为籍屏蔽我，我很公道的说，我没有做对不起他们两个的事情，人格担保，可能是我平常一些行为让他们讨厌了吧；我挺直的，喜欢不喜欢都挂在嘴边，这应该是作为我嘴臭讨厌我的理由，但这不只我一个人；太明显的针对了，而且证据也有，我藏进了第四周目截图里。目的太明显了，我都不知道对我这么强烈的恨是什么。
> 谢谢，如果可以留下来，万分感谢
> 这样公道的处理对我已经是最善良的结果了。

没错,我也很不解,但是你的言行因该在群内和游戏中规范一些,她们这种行为是破坏他人游戏体验的,所有人可以选择屏蔽别人，但若继续干涉则是她们的不对,你虽然刷物品但是我也同时可以惩罚她们的游戏不当行为,由于刷物品之事率先发生，因此我只能把你账号封禁免除踢出(因为你首先触发服务器规则底线)但由于你个人原因,与he一起玩的游戏体验被破坏后，我决定将你**继续留在群内**,只不过你得重**新注册账号**重新玩。

为什么我没有对他人做出惩罚?因为她两并未触及服务器规则问题，但是她们的行为可以解释你的一部分行为，因此我决定将你继续留在群内 :3。

今日后的频道改善及二群组队群,我会创建第二个群用来专门组队用,并且服务器也会有多个频道,你若觉得她们说话难受你可以去往另外一个频道,但若她们在新人面前贬低人你可以直接告诉我。另外，请不要刷物品,你刷物品你将失去所有主动权因为刷物品是服务器的首要规则，其他规则都是在这规则之后,若你不刷物品她们会有完全的“**错**”。

同时,我也会监督群内的喷人骂人等情况,在这事情之后,任何在频道中人生攻击的人一律踢出服务器。

**Comment by Threxion** [comment]
嗯，谢谢，她还不会直接用贬低我这样低级的手段，谢谢了

**Comment by Threxion** [comment]
不会辜负二位的信任的。

**Comment by Rubywu-Xin** [comment]
是的,在上次追寻你和NXX聊天记录时附带查了前几天的，这事可以证实的

**Comment by Caishangqi** [comment]
此条文存在信息真实性，因此失效!

**Comment by Rubywu-Xin** [comment]
> ## 此条文存在信息真实性，因此失效!

## 双方矛盾 `wight` 和 `very_nice` 事件中证人 `he_xiao_you` 其本身信息存在偏差因此失去作为证人的资格,此次事件没有任何一方说出的话语完全正确, 请其他玩家谨慎看待此事件。
