### ISSUE TITLE
对服务器发展的一些建议和一些bug提交

### ISSUE THREAD

**Issue by Threxion** [Caishangqi/GonerAge#6]
Bug：
1.在玩家速度过快时会被服务器“拉住”，是在fly权限关掉以后
具体表现是带了琥珀金配件的武器在蓄能攻击后获得速度四后进行跳跃，会被服务器拉回去，跳不了
2.睡觉貌似并不能重置游戏难度（丧）
3.匠魂有好多强化消失了😏
对服务器的发展建议:
1.啊合金的话可以采用矿+某兑换材料=合金溶液？
匠魂只要ban放置冶炼炉控制器应该就没毛病了
2.🙏希望把wight变成主城npc

**Comment by Caishangqi** [comment]
限速 0.7 可以调整至更高
睡觉降低难度为0.00023
服务器每秒增加难度 0.00000078
具体列出强化消失名单
合金等待作者修复此问题 #2

**Comment by HeXiaoYou** [comment]
<img width="324" alt="截屏2020-06-16 上午9 04 31" src="https://user-images.githubusercontent.com/66977341/84720414-93620180-afb0-11ea-92b0-e629150db06c.png">
<img width="354" alt="截屏2020-06-16 上午9 04 43" src="https://user-images.githubusercontent.com/66977341/84720421-978e1f00-afb0-11ea-97a6-85a533bb7da2.png">
<img width="322" alt="截屏2020-06-16 上午9 05 09" src="https://user-images.githubusercontent.com/66977341/84720436-a07ef080-afb0-11ea-9806-997c6fd70eaa.png">
经过对工具强化的测试，发现经验修复强化失效，并且从匠魂宝典中移除，其余工具强化无问题

**Comment by Threxion** [comment]
1.老大鸽，我又来了
2.神秘的奥术工作台貌似只能用合成台做而不是正常配方工作台（？）虽然没什么差别，我老nt了
商店可以售卖比如匠魂的凋零之骨之类的东西，而且物价钛便宜了（对我而言，虽然那些东西都很基础），希望可以高价售卖后期基础物品，如硅板等等（电气时代入门芯片任务制作的材料）
3.暮色boss娜迦打着打着就bug了，成为了未知实体，可以被攻击，可以被观测，可以破坏地形，但是无法杀死，只剩下一个头，保有基本行动AI（恐怖片？）；以至于无法继续探索
4.希望可以添加可兑换称号，如收集整套唱片的“电音之王”,“橡胶人”......
5.wsm主城的npc有两对眼睛？hxd？kkp

**Comment by Caishangqi** [comment]
> <img alt="截屏2020-06-16 上午9 04 31" width="324" src="https://user-images.githubusercontent.com/66977341/84720414-93620180-afb0-11ea-92b0-e629150db06c.png">
> 
> <img alt="截屏2020-06-16 上午9 04 43" width="354" src="https://user-images.githubusercontent.com/66977341/84720421-978e1f00-afb0-11ea-97a6-85a533bb7da2.png">
> 
> <img alt="截屏2020-06-16 上午9 05 09" width="322" src="https://user-images.githubusercontent.com/66977341/84720436-a07ef080-afb0-11ea-9806-997c6fd70eaa.png">
> 
> 经过对工具强化的测试，发现经验修复强化失效，并且从匠魂宝典中移除，其余工具强化无问题

人为移除,这东西不符合社会主义核心价值观
`S:"Remove Modifiers" <
        mending_moss
     >`

**Comment by Threxion** [comment]
hello again！我又来了！这次是一个很傻逼的bug
实用性：0 娱乐性：1000
拿着菜在主城地板上放下会刷出盘子
无限刷

**Comment by Caishangqi** [comment]
> hello again！我又来了！这次是一个很傻逼的bug
> 实用性：0 娱乐性：1000
> 拿着菜在主城地板上放下会刷出盘子
> 无限刷

收到,下次版本更新时修复

**Comment by Threxion** [comment]
xinxi姐把我赶来了
5 5 5
*神秘银树和宏伟木板不能合成
太草了
据木头的工作台造的木头没手搓得多差评（小声bb
wight不是op差评
*然后是发现carryon有时候在搬蜂箱（未来mc的野生蜂箱）时会触发bug，无限放
wight不能秒boss
*以及地狱太安全了，我想当op来产怪，地狱不该是和和气气的！
地狱应该充满妹子！（我就想想就好）
芜湖！
这波啊，这波是bug葱鸡
