### ISSUE TITLE
传送之后会有后摇

### ISSUE THREAD

**Issue by 1504879303** [Caishangqi/GonerAge#8]
导致大部分清空会被蹲点然后无限死亡

**Comment by Caishangqi** [comment]
传送本身有3.5秒无敌时间,但是如果取消后摇那么意味着在打boss时候可以随时传送至安全位置,难度降低,可以修改传送无敌时间至5秒但是不能取消后摇

**Comment by 1504879303** [comment]
3.5s完全没有感觉，昨天一个冒火的200血傀儡贴脸杀

**Comment by Caishangqi** [comment]
> 3.5s完全没有感觉，昨天一个冒火的200血傀儡贴脸杀

因为是以传送指令发送为准,中间会有网络延迟+地形生成

**Comment by 1504879303** [comment]
但是传送指令输完被打还是会被取消，所有感觉这无敌直接被吃了

**Comment by 1504879303** [comment]
能不能back默认旁观者，然后捡起东西就回复，不要无敌了。

**Comment by Caishangqi** [comment]
> 能不能back默认旁观者，然后捡起东西就回复，不要无敌了。

旁观者模式要怎么点到物品呢 :3

**Comment by 1504879303** [comment]
也是：（
